a = int (input ('Enter the Value of A :'))
b = int (input ('Enter the Value of B :'))
print ("Addition of a and b :",a+b)
print ("Subrtraction of a and b :", a-b)
print ("Multiplaction of a and b :", a*b)
print ("Divivsion of a and b :", a/b)
print ("Floor Divison of a and b :", a//b)
print ("Modules Division of a and b :", a%b)
print ("a power of b :",a**b)