list1=[20,10,30,50,40]
print('Prinitng the existing List 1 : ',list1)
print('Type of the List 1 precreated : ',type(list1))
str1="This is a String converted to List"
list2=str1.split()
print('Printing teh String in to list : ',list2)
print("First word in the list 2",list2[0])
print("Second word from the last in list 2",list2[-2])
print("One word with 1 skipping in List 2",list2[::2])
print ('---------------------------------------------')
print ('length of List 1 :',len(list1))
print ('count of 10 in list 1 :', list1.count(10))
#print ('index of 10 in list 1 :',list1.index(10))
n1 = int(input('Enter a value that need to appended in List 1 : '))
list1.append(n1)
print ("Modfified list 1 : ",list1)
n2 = int(input('Enter a value that need to be inserted in List 1 :'))
p1 = int(input('Enter the position which we need to insert in List 1 :'))
list1.insert(p1,n2)
print("Updated List 1 : ",list1)
print('----------------------------------------------')
r1=int(input('Enter the number that need to remove from the list 1 :'))
list1.remove(r1)
print('Latest List 1 : ',list1)
r2=int(input('Pop the element from the list 1 :'))
list1.pop(r2)
print('new version of list 1 :',list1)
#print('sorted of the lsit 1 :',list1.sort())
#print('revere of the list 1 : ',list1.reverse())
print('---------------------------------------------------')
print("Extending List 1 and List 2 : ", list1.extend(list2))
print(list1)
print('------------------------------------')
list3=['1','2','3']
list4=['4','5','6']
print('List 4',list4)
print('List 3',list3)
print('adding the list 3 and list 4',list3+list4)